---
# defaults file for ldomb-rhhi

ssh_priv_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAwIVuHbity+0lN5ZGuF+yJlSjimkHf9jz9EXN640XBtj5P2bA
  LOn8AH3BJf0SJWlhnE1k/TvFr7FaFFtE5hcjvzLWEq9htF/6usN81wAAHDGEZG3c
  2zm40wk63oP5OfKlzCVMBHBG57/gA+RigUzivuVNhsthaFRYAOtwEkQLCUm4/T1s
  q4VD1vyTolE6++1Trg86H3kVPvXMxa1moFqnWX7h3HDWPWDn982LzQuU8s/tLhBA
  QW138fK7Al5gUEP/hOLSyQn//dom17r14KdR8P+wW/cOPok/z7nv9bel4l5M0FSz
  i2StHLMBXrJhgxk8SVXf8l6EWcvm+bAMCA/5ywIDAQABAoIBAHwy2BoWdRB02ail
  qtPw8HXn7mUxYqQoqyDwE2sdZziEqy8qs1mGTYtnlT5Tp+w4sr7p8venIt44NNuj
  Eay6StZjDlWZjReXP6JS0OvG1Uta6oT7lxpaf5CtiKvaSeMHVcyAVy0Z3bRORU9d
  e+rcVf8+4KfP9vQeTXOyb2dpPBFtvo3QgX9jdkKEIu6Zu/QukG232CFy9jntbmu0
  +Dzpl6Ea1tJbNOZb4/hsc5j6qzMpoGAD6AlxA9KeOiLohfL/MyDR1fCdjjFdoOOh
  uJsvTK5JCUlSg5q+2sd6LiEU03ZxAK+5jqurdXUeSXSGO9FOkLGyc+lIRzpDjT6B
  xKBG6yECgYEA4bnW0XLbv4YoMNsRtbfvhzwE4U2xsedMmaQkOWnB59Ap/JC0BZPj
  aJgxfe83VbcI6FlwBCyKDPL5Ip29wcxnkri005zmgal6gD0De5jpBMoLmjwC8IGe
  z9PCfymFyOZZRfy0LTFvgq0uDbXpNLTywHD6hLARvaapczDTa9KQLTsCgYEA2leG
  /iL/YQ0srvVDIEGe6a71UZy5aLOoJ/oRH8ixb/BlsuSJI9k3lZfuR/lRNyOTmjvz
  +zZMs3JMatJ8UfuLJ2Bv287y7vQOvfy810kt0UHHZZ5zOsOdqzTSyr/WNhH9j1/+
  MYmUYCVra53KtHJLHdn/M5aPc28W82M9jDJm3LECgYBbsWAgCOZXMKoW3oadKLC2
  YJ0i4Kq0N98X8mN8pwdLoXXM0QMv2Nlh3aENJSV3PjjyGZK1P1p81B57/1Pb66qP
  IVTjOTMxrKTEfwRxKrZNab2403PmOuFGTyENAtMDvv64vWR7jz9a9/pjO2gWLwMF
  RV+ekt9CCPeAgW8At7I1jQKBgQCHGVdu0mrgO02lqB5zzAavI1GpwOa8UUXADqwf
  1Yds8vuKWHw+0T3icxK+OBc3nezLp0MM8ok9E4ETK9A+zf1JTROJl6CbmCmzBro2
  H5KZAzGEwCkeeEGL2PCBAXhjFnilCUl4j19eqmiwOv9c7cdq3iNZYVS7oUY7LPG9
  WMZq0QKBgBGnqwnKaQ9fFnR/E9V5OXnVPJf0zwbc+FPOk6ts6DfQDf9itlRj+oPJ
  yu4mp0f8Ze8ZPtartNmh/vWaQm72eJdYdE0SXHKH0N6KOzWTogcvv3xjs0xEJHPu
  y5SI0N9fh82hPSwgRjejvLk/jie08b3sGxGmx6BRXYhKyvLqhOd0
  -----END RSA PRIVATE KEY-----

