- name: Play to setup the git repo and kvm for automation
  hosts: 127.0.0.1
  remote_user: root
  vars:
    ansible_ssh_user: root
    ansible_ssh_pass: redhat
  tasks:
  - name: check that KVM is online
    wait_for:
      host: "{{ inventory_hostname }}"
      state: started
      connect_timeout: 5
      timeout: 300
      port: 22
    delegate_to: 127.0.0.1
    become: false
    ignore_errors: true

  - name: add authorized key from machine running this playbook
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: Clone the code repository to /root
    git:
      repo: "https://github.com/redhat-kejones/hattrick.git"
      dest: /root/hattrick
      accept_hostkey: yes
    when: disconnected is not defined

  - name: Copy vault sample
    copy:
      src: /root/hattrick/group_vars/all/vault.sample
      dest: /root/hattrick/group_vars/all/vault
      remote_src: yes
    when: disconnected is not defined

  - debug:
      msg:
        - "Now you need to populate your Ansible vault file:"
        - "# ansible-vault encrypt /root/hattrick/group_vars/all/vault"
        - "# ansible-vault edit /root/hattrick/group_vars/all/vault"
