---
- hosts: rhosp_director
  name: playbook to shutdown all hattrick systems and services
  gather_facts: false
  remote_user: root
  become_user: stack
  tasks:
  - name: Authenticate to the cloud and retrieve the service catalog
    os_auth:
      auth:
        auth_url: "{{ osp_url }}"
        username: "{{ osp_user }}"
        password: "{{ osp_pass }}"
        project_name: "{{ osp_project }}"

  - name: get list of openstack projects
    os_project_facts:
      auth:
        auth_url: "{{ osp_url }}"
        username: "{{ osp_user }}"
        password: "{{ osp_pass }}"
        project_name: "{{ osp_project }}"

  - os_server_facts:
      auth:
        auth_url: "{{ osp_url }}"
        username: "{{ osp_user }}"
        password: "{{ osp_pass }}"
        project_name: "{{ osp_project }}"
    with_items:
      - "{{ openstack_projects }}"

  - os_server_action:
      action: stop
      auth:
        auth_url: "{{ osp_url }}"
        username: "{{ osp_user }}"
        password: "{{ osp_pass }}"
        project_name: "{{ osp_project }}"
      server: "{{ item.name }}"
      timeout: 200
    with_items:
      - "{{ openstack_servers }}"

  - name: get provisioning IPs for overcloud hosts
    become: yes
    become_user: stack
    shell: "source /home/stack/stackrc && openstack server list -c Networks --format value | cut -d = -f 2"
    register: overcloud_host_prov_ips

  - name: poweroff overcloud hosts
    become: yes
    become_user: stack
    command: "ssh heat-admin@{{ item }} sudo poweroff"
    with_items:
      - "{{ overcloud_host_prov_ips.stdout_lines }}"
    async: 1
    poll: 0
    ignore_errors: true

  - name: waiting for overcloud hosts to poweroff
    wait_for:
      host: "{{ item }}"
      state: stopped
      delay: 10
      connect_timeout: 5
      timeout: 300
      port: 22
    delegate_to: 127.0.0.1
    become: false
    ignore_errors: true
    with_items:
      - "{{ overcloud_host_prov_ips.stdout_lines }}"

  - name: poweroff Undercloud
    shell: sleep 2 && /sbin/shutdown -c && /sbin/shutdown -h now
    async: 1
    poll: 0
    ignore_errors: true

  - name: waiting for Undercloud to poweroff
    wait_for:
      host: "{{ inventory_hostname }}"
      state: stopped
      delay: 10
      connect_timeout: 5
      timeout: 300
      port: 22
    delegate_to: 127.0.0.1
    become: false
    ignore_errors: true

- hosts: rhel_idm
  name: play to shutdown IDM
  gather_facts: false
  remote_user: root
  tasks:
  - name: poweroff IDM
    shell: sleep 2 && /sbin/shutdown -c && /sbin/shutdown -h now
    async: 1
    poll: 0
    ignore_errors: true

  - name: waiting for IDM to poweroff
    wait_for:
      host: "{{ inventory_hostname }}"
      state: stopped
      delay: 10
      connect_timeout: 5
      timeout: 300
      port: 22
    delegate_to: 127.0.0.1
    become: false
    ignore_errors: true

- hosts: rhel_kvm
  name: play to shutdown KVM
  gather_facts: false
  remote_user: root
  tasks:
  - name: poweroff KVM
    shell: sleep 2 && /sbin/shutdown -c && /sbin/shutdown -h now
    async: 1
    poll: 0
    ignore_errors: true

  - name: waiting for KVM to poweroff
    wait_for:
      host: "{{ inventory_hostname }}"
      state: stopped
      delay: 10
      connect_timeout: 5
      timeout: 300
      port: 22
    delegate_to: 127.0.0.1
    become: false
    ignore_errors: true
