###############################################################################
### Project Hat Trick is an Open Architecture approach to defining and      ###
### automating the deployment of Red Hat Software Bundles on open,          ###
### commodity hardware. The architectures and automation developed here     ###
### can be utilized as a starting place for applying this in a datacenter   ###
### installation.                                                           ###
###                                                                         ###
### Option 1: RH OpenStack Platform and Ceph Hyperconverged                 ###
###                                                                         ###
### Enjoy and Contribute!                                                   ###
###############################################################################

#Configure Network Gear
#- import_playbook: 01-netgear-switch-config.yml

- name: install and configure RHEL KVM
  import_playbook: 02-rhel7-kvm.yml
  tags: rhel_kvm

- name: create VMs for infrastructure services
  tags: infrastructure
  import_playbook:  03.1-vmenator.yml

- name: create VMs for infrastructure services
  tags: infrastructure
  import_playbook:  03.2-wait-for-vms.yml

- name: install and configure IDM
  tags: infrastructure
  import_playbook:  03.3-rhel7-idm-install.yml

- name: install and configure reposync server
  tags: infrastructure
  import_playbook:  03.3-rhel7-repo-install.yml

- name: install and configure RHOSP director
  tags: infrastructure
  import_playbook:  03.3-rhosp-director-install.yml

#- import_playbook:  04-rhosp-overcloud-deploy-prep.yml

#RHOSP Overcloud deployment
#- import_playbook:  05-rhosp-overcloud.yml

#RHOSP Overcloud Post Configuration
#- import_playbook:  06-rhosp-overcloud-post-config.yml

#Deploy simple RHEL7 host with Ansible Engine and OpenStack Shade on RHOSP
#- import_playbook:  07-rhel7-ansible-engine-plus-shade.yml

#Deploy Ansible Tower on RHOSP
#- import_playbook:  08-ansible-tower.yml

#Deploy and configure CloudForms (1 DB, 1 Worker, 1 UI) on RHOSP
#- import_playbook:  09-rhcloudforms.yml

#Deploy OpenShift Container Platform on RHOSP
#- import_playbook:  10-rhocp.yml
