---
- hosts: rhosp_director
  name: playbook to startup all hattrick systems and services
  remote_user: root
  tasks:
  - name: startup overcloud hosts
    command: "for i in {1..4}; do ironic node-set-power-state node$i on; done"

  - name: waiting for horizon to come online
    wait_for:
      host: "192.168.1.40"
      state: started
      delay: 10
      connect_timeout: 5
      timeout: 300
      port: 80
    delegate_to: 127.0.0.1
    become: false
    ignore_errors: true

  - name: get list of openstack projects
    os_project_facts:
      cloud: overcloud

  - debug:
    var: openstack_projects
