---
#TODO: Need to find or write playbook to prep initial host to be KVM, Gateway,
#      and with networking in place
- hosts: localhost
  name: create infrastructure VMs
  remote_user: kejones
  become: yes
  roles:
    - vmenator
