---
# tasks file for roles/rhel-common
- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false

- name: register System with RHN Subscription Manager
  redhat_subscription:
    state: present
    username: "{{ rhn_user }}"
    password: "{{ rhn_pwd }}"
    pool: "{{ rhn_pool_name }}"
  when: ansible_distribution == 'RedHat' and register_rhn

- name: disable all repositories
  command: subscription-manager repos --disable=\*
  when: ansible_distribution == 'RedHat' and register_rhn

- name: enable the needed rhel repositories
  command: subscription-manager repos --enable={{ item }}
  with_items:
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
  when: ansible_distribution == 'RedHat' and register_rhn
