---
# tasks file for roles/rhosp_overcloud
- name: copy deploy.sh script
  become: yes
  become_user: stack
  template:
    src: "templates/deploy-{{ versions.rhosp }}.sh.j2"
    dest: /home/stack/deploy.sh
    owner: stack
    group: stack
    mode: 0775
  tags: pre-overcloud

- name: copy director templates
  become: yes
  become_user: stack
  copy:
    src: "files/templates-{{ versions.rhosp }}/"
    dest: /home/stack/templates
    owner: stack
    group: stack
  tags: pre-overcloud

- name: copy cloudname.yaml template
  become: yes
  become_user: stack
  template:
    src: "templates/templates-{{ versions.rhosp }}/cloudname.yaml.j2"
    dest: /home/stack/templates/cloudname.yaml
    owner: stack
    group: stack
  tags: pre-overcloud

- name: copy network-environment.yaml template
  become: yes
  become_user: stack
  template:
    src: "templates/templates-{{ versions.rhosp }}/network-environment.yaml.j2"
    dest: /home/stack/templates/network-environment.yaml
    owner: stack
    group: stack
  tags: pre-overcloud

- name: copy storage-environment.yaml template
  become: yes
  become_user: stack
  template:
    src: "templates/templates-{{ versions.rhosp }}/storage-environment.yaml.j2"
    dest: /home/stack/templates/storage-environment.yaml
    owner: stack
    group: stack
  tags: pre-overcloud

- name: copy timezone.yaml template
  become: yes
  become_user: stack
  template:
    src: "templates/templates-{{ versions.rhosp }}/timezone.yaml.j2"
    dest: /home/stack/templates/timezone.yaml
    owner: stack
    group: stack
  tags: pre-overcloud

- name: deploy RHOSP overcloud
  become: yes
  become_user: stack
  shell: |
    /home/stack/deploy.sh > /home/stack/overcloud-deploy.log 2>&1
  args:
    chdir: /home/stack
  #async: 3660
  #poll: 60
  tags: deploy-overcloud

- name: create folder for guest_images
  file:
    path: /home/stack/guest_images
    state: directory
    owner: stack
    group: stack
    mode: 0775

- name: copy guest_images to Undercloud
  synchronize:
    src: guest_images/*.qcow2
    dest: /home/stack/guest_images


#TODO: Need to convert this script to ansible tasks
- name: copy overcloud post config script
  become: yes
  become_user: stack
  template:
    src: "templates/overcloudPostConfig.sh.j2"
    dest: /home/stack/overcloudPostConfig.sh
    owner: stack
    group: stack
    mode: 0775
  tags: post-overcloud

- name: run overcloud post configuration
  become: yes
  become_user: stack
  shell: |
    /home/stack/overcloudPostConfig.sh \
    > /home/stack/overcloud-post-deploy.log 2>&1
  args:
    chdir: /home/stack
  #async: 300
  #poll: 10
  tags: post-overcloud
  ignore_errors: true #TODO: Remove later
