---
- name: add local repo to rhel client
  hosts: "{{ hostname_to_stig }}"
  gather_facts: true
  vars_files:
      - '../../../group_vars/all/vars'
      - '../../../group_vars/all/hattrick'

  tasks:
  - name: enable the needed rhel repositories
    yum_repository:
      name: "{{ item }}"
      description: "{{ item }}"
      baseurl: "{{ local_repo_url }}{{ item }}"
      gpgcheck: no
      enabled: yes
      file: rhn-local
      state: present
    with_items:
      - "{{ rhel_repo.repos.rhel }}"
