---
# tasks file for roles/rhel_common
- name: import secret variable file
  include_vars: "vault"
  no_log: true

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false

- name: register System with RHN Subscription Manager
  redhat_subscription:
    state: present
    username: "{{ rhn_user }}"
    password: "{{ rhn_pwd }}"
    pool: "{{ rhn_pool_name }}"
  when: ansible_distribution == 'RedHat' and register_rhn

- name: disable all repositories
  command: subscription-manager repos --disable=\*
  when: ansible_distribution == 'RedHat' and register_rhn
