---
- hosts: rhosp_director
  name: playbook to shutdown all hattrick systems and services
  remote_user: root
  become_user: stack
  tasks:
  - name: Authenticate to the cloud and retrieve the service catalog
    os_auth:
      auth:
        auth_url: "{{ osp_url }}"
        username: "{{ osp_user }}"
        password: "{{ osp_pass }}"
        project_name: "{{ osp_project }}"

  - name: Show service catalog
    debug:
      var: service_catalog

  - name: get list of openstack projects
    os_project_facts:
      auth:
        auth_url: "{{ osp_url }}"
        username: "{{ osp_user }}"
        password: "{{ osp_pass }}"
        project_name: "{{ osp_project }}"

  - debug:
    var: openstack_projects

  #TODO: should I loop over projects and stop all vms?
  #      or just operators project vms?

  - os_server_facts:
      auth:
        auth_url: "{{ osp_url }}"
        username: "{{ osp_user }}"
        password: "{{ osp_pass }}"
        project_name: "{{ osp_project }}"
  
  - debug:
    var: openstack_servers

  - os_server_action:
      action: stop
      auth:
        auth_url: "{{ osp_url }}"
        username: "{{ osp_user }}"
        password: "{{ osp_pass }}"
        project_name: "{{ osp_project }}"
      server: {{ item.name }}
      timeout: 200
    with_dict: openstack_servers

  - name: get provisioning IPs for overcloud hosts
    become: yes
    command: "source /home/stack/stackrc && openstack server list -c Networks | awk '/192.168.2/ {print $2}' | cut -d = -f 2"
    register: overcloud_host_prov_ips

  - name: poweroff overcloud hosts
    command: "ssh heat-admin@{{ item.value }} sudo poweroff"
    with_items:
      - "{{ overcloud_host_prov_ips.stdout_lines }}"

  - name: waiting for overcloud hosts to poweroff
    wait_for:
      host: "{{ item.value }}"
      state: stopped
      delay: 10
      connect_timeout: 5
      timeout: 300
      port: 22
    delegate_to: 127.0.0.1
    become: false
    ignore_errors: true
    with_items:
      - "{{ overcloud_host_prov_ips.stdout_lines }}"

- hosts: rhel_idm
  name: play to shutdown IDM
  remote_user: root
  tasks:
  - name: poweroff IDM
    command: "poweroff"

  - name: waiting for IDM to poweroff
    wait_for:
      host: "{{ inventory_hostname }}"
      state: stopped
      delay: 10
      connect_timeout: 5
      timeout: 300
      port: 22
    delegate_to: 127.0.0.1
    become: false
    ignore_errors: true

- hosts: rhel_kvm
  name: play to shutdown KVM
  remote_user: root
  tasks:
  - name: poweroff KVM
    command: "poweroff"

  - name: waiting for KVM to poweroff
    wait_for:
      host: "{{ inventory_hostname }}"
      state: stopped
      delay: 10
      connect_timeout: 5
      timeout: 300
      port: 22
    delegate_to: 127.0.0.1
    become: false
    ignore_errors: true
